export const addresses = [
  {
    city: "Sztokholm",
    groupName: "Odenplan",
    street: "Karlbergsvägen 32B",
    date: "Niedziela",
    time: "20:00",
    coordinate: [59.34294, 18.0436],
    popup: "Miejsce spotkań - wejście do piwnicy",
    openDay: "Ostatnia niedziela miesiąca",
  },
  {
    city: "Sztokholm",
    groupName: "Nadzieja",
    street: "Södermannagatan 52",
    date: "Niedziela",
    time: "18:00",
    coordinate: [59.30967, 18.079869],
    popup: "Miejsce spotkań",
    openDay: "Ostatnia niedziela miesiąca",
  },
  {
    city: "Vendelsö",
    groupName: "Stella Maris",
    street: "Vendelsömalmsvägen 200",
    date: "Sobota",
    time: "19:00",
    coordinate: [59.17548, 18.16751],
    popup: "Kościół Katolicki",
    openDay: "Ostatnia sobota miesiąca",
  },
  {
    city: "Märsta",
    groupName: "Pojednanie",
    street: "Stockholmsvägen 50",
    date: "Piątek",
    time: "19:00",
    coordinate: [59.62626 ,17.84387],
    popup: "Wejście do salki przez główne drzwi kościoła",
    openDay: "Ostatni piątek miesiąca",
  },
];
